# Generated by Django 3.2.4 on 2021-12-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0002_auto_20211122_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe_do_Item',
            fields=[
                ('classe_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_do_Item',
            fields=[
                ('grupo_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('classe_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.classe_do_item')),
                ('grupo_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.grupo_do_item')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Produto',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('unidade', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('fator', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadeentrada', models.CharField(blank=True, max_length=50, null=True)),
                ('fatorconversao', models.FloatField(default=0)),
                ('inativo', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.cla')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.git')),
            ],
        ),
        migrations.CreateModel(
            name='Item_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('data_ultima_compra', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('altura_espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.qualidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.tipo_produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
            ],
        ),
    ]
