# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bens', '0001_initial'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_do_Produto',
            fields=[
                ('categoria_do_produto', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe_do_Item',
            fields=[
                ('classe_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe_do_Produto',
            fields=[
                ('classe_do_produto', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_do_Item',
            fields=[
                ('grupo_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_do_Produto',
            fields=[
                ('grupo_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('classe_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.classe_do_item')),
                ('grupo_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.grupo_do_item')),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=150, null=True)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadeentrada', models.CharField(blank=True, max_length=50, null=True)),
                ('inativo', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.cla')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.git')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Produto',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('unidade', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('fator', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_Produto',
            fields=[
                ('unidade', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('fator', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'ATENDIDO'), ('C', 'CANCELADO')], default='P', editable=False, max_length=1)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bens.bem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.pro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.uni')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=150, null=True)),
                ('inativo', models.BooleanField(default=False)),
                ('valor', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria_do_produto')),
                ('classe_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.classe_do_produto')),
                ('grupo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.grupo_do_produto')),
                ('unidade_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.unidade_produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('data_ultima_compra', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('altura_espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.tipo_produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.pro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.uni')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
