# Generated by Django 3.2.4 on 2021-11-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_do_Item',
            fields=[
                ('classe_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_do_Item',
            fields=[
                ('grupo_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('classe_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.classe_do_item')),
                ('grupo_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.grupo_do_item')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Produto',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('data_ultima_compra', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('altura_espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.qualidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.tipo_produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
            ],
        ),
    ]
