# Generated by Django 3.2.4 on 2021-10-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_do_Item',
            fields=[
                ('classe_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_do_Item',
            fields=[
                ('grupo_do_item', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('classe_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.classe_do_item')),
                ('grupo_do_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.grupo_do_item')),
            ],
        ),
    ]
