# Generated by Django 3.2.4 on 2021-12-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20211122_1334'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.empresa'),
            preserve_default=False,
        ),
    ]
