# Generated by Django 3.2.4 on 2021-12-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0002_req_aplicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.pro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.uni')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
