# Generated by Django 3.2.4 on 2021-12-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20211122_1334'),
        ('estoque', '0002_pro_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('data', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.aplicacao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.pro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.uni')),
            ],
        ),
    ]
