# Generated by Django 3.2.4 on 2021-12-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_entrada_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='fatorconversao',
        ),
    ]
