# Generated by Django 3.2.4 on 2021-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='apelido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
