# Generated by Django 3.2.4 on 2021-12-07 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_pro_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='req',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
