# Generated by Django 3.2.4 on 2022-04-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_pro_fatorconversao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='qualidade',
        ),
    ]
