# Generated by Django 3.2.4 on 2021-12-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20211207_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='status',
        ),
    ]
