# Generated by Django 3.2.4 on 2021-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='status',
            field=models.NullBooleanField(default=False),
        ),
    ]
