# Generated by Django 3.2.4 on 2021-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_req_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
