# Generated by Django 3.2.4 on 2021-12-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_req_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='status',
        ),
    ]
