# Generated by Django 3.2.4 on 2021-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('A', 'ATENDIDO'), ('C', 'CANCELADO')], default='P', max_length=1),
        ),
    ]
