# Generated by Django 3.2.4 on 2021-12-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20211122_1334'),
        ('estoque', '0010_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa'),
        ),
    ]
