# Generated by Django 3.2.4 on 2021-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_pro_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.CharField(max_length=100)),
            ],
        ),
    ]
