# Generated by Django 3.2.4 on 2021-12-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_apl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.apl'),
        ),
    ]
