# Generated by Django 3.2.4 on 2021-12-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_alter_req_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='empresa',
        ),
    ]
