# Generated by Django 3.2.4 on 2021-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_remove_req_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='aplicacao',
        ),
        migrations.AlterField(
            model_name='req',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('A', 'ATENDIDO'), ('C', 'CANCELADO')], default='P', editable=False, max_length=1),
        ),
    ]
