# Generated by Django 3.2.4 on 2021-12-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_auto_20211208_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='aplicacao',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='estoque.apl'),
            preserve_default=False,
        ),
    ]
