# Generated by Django 3.2.4 on 2021-12-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_req_aplicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='req',
            old_name='nome',
            new_name='item',
        ),
    ]
