# Generated by Django 3.2.4 on 2021-12-09 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_rename_nome_req_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 9, 13, 13, 0, 438779, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pro',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='req',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='req',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
