# Generated by Django 3.2.4 on 2021-07-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0028_view_producao_fio_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custos_Gerais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(default=2021)),
                ('mes', models.IntegerField(choices=[(1, 'JANEIRO'), (2, 'FEVEREIRO'), (3, 'MARÇO'), (4, 'ABRIL'), (5, 'MAIO'), (6, 'JUNHO'), (7, 'JULHO'), (8, 'AGOSTO'), (9, 'SETEMBRO'), (10, 'OUTUBRO'), (11, 'NOVEMBRO'), (12, 'DEZEMBRO')])),
                ('producao_m2', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_de_Producao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_de_producao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Custos_Gerais_Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custos_gerais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.custos_gerais')),
                ('item_de_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
            ],
        ),
    ]
