# Generated by Django 3.2.4 on 2021-07-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custos_gerais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custo_item', models.CharField(default='indefinido', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Item_de_Producao',
        ),
        migrations.RemoveField(
            model_name='custos_gerais_itens',
            name='item_de_producao',
        ),
        migrations.AddField(
            model_name='custos_gerais_itens',
            name='custo_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.custo_item'),
        ),
    ]
