# Generated by Django 3.2.4 on 2021-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos_gerais', '0002_auto_20210730_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_gerais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
