# Generated by Django 3.2.4 on 2021-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos_gerais', '0003_alter_custos_gerais_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custo_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
