# Generated by Django 3.2.4 on 2021-08-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custos_gerais', '0004_alter_custo_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo_Geral_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_de_Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_de_producao', models.CharField(default='indefinido', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='custos_gerais_itens',
            name='custo_item',
        ),
        migrations.RemoveField(
            model_name='custos_gerais_itens',
            name='custos_gerais',
        ),
        migrations.RenameModel(
            old_name='Custos_Gerais',
            new_name='Custo_Geral',
        ),
        migrations.DeleteModel(
            name='Custo_Item',
        ),
        migrations.DeleteModel(
            name='Custos_Gerais_Itens',
        ),
        migrations.AddField(
            model_name='custo_geral_item',
            name='custo_geral_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.custo_geral'),
        ),
        migrations.AddField(
            model_name='custo_geral_item',
            name='item_de_producao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.item_de_producao'),
        ),
    ]
