# Generated by Django 3.2.4 on 2021-08-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custos_gerais', '0005_auto_20210802_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custo_geral_item',
            old_name='item_de_producao',
            new_name='item_de_producao_id',
        ),
    ]
