# Generated by Django 3.2.4 on 2021-08-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0028_view_producao_fio_resumo'),
        ('custos_gerais', '0006_rename_item_de_producao_custo_geral_item_item_de_producao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custo_geral_item',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='custo_geral_item',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade'),
        ),
    ]
