# Generated by Django 3.2.4 on 2021-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_auto_20211116_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_de_venda',
            name='localizacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
