# Generated by Django 3.2.4 on 2022-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_produto_de_venda_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_de_venda',
            name='qualidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
