# Generated by Django 3.2.4 on 2021-11-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_produto_de_venda_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_de_venda',
            name='vendido',
            field=models.FloatField(default=0),
        ),
    ]
