# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha_Resinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Resinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade_de_chapas', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resinagem.linha_resinagem')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Resinagem_tela_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField()),
                ('chapa_final', models.IntegerField()),
                ('quantidade_insumo', models.FloatField(default=0)),
                ('resina', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item_de_almoxarifado', verbose_name='Tela')),
                ('resinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resinagem.resinagem', verbose_name='Chapa número')),
                ('unidade', models.ForeignKey(default='M', on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Resinagem_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('frequencia', models.PositiveIntegerField(default=1)),
                ('resina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item_de_almoxarifado')),
                ('resinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resinagem.resinagem', verbose_name='Insumo')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade_de_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item_de_almoxarifado')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade_de_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Chapas_resinadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField()),
                ('chapa_final', models.IntegerField()),
                ('resinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resinagem.resinagem', verbose_name='Chapa número')),
            ],
        ),
    ]
