# Generated by Django 3.2.4 on 2023-02-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade_de_Medida',
            fields=[
                ('unidade', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fator', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_de_Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantidade', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.unidade_de_medida')),
            ],
        ),
    ]
