# Generated by Django 3.2.4 on 2023-02-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_de_almoxarifado',
            name='setor',
        ),
    ]
