# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0001_initial'),
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grao', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa')),
                ('usuario_cadastrou', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo_de_Abrasivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=6)),
                ('valor_abrasivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalizado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('abrasivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.abrasivo')),
            ],
            options={
                'verbose_name': 'Jogo de Abrasivo',
                'verbose_name_plural': 'Jogo de Abrasivos',
            },
        ),
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('qualidade', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_polimento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Polimento',
                'verbose_name_plural': 'Tipos de Polimentos',
            },
        ),
        migrations.CreateModel(
            name='Set_de_Abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.maquina')),
                ('set_de_abrasivos', models.ManyToManyField(limit_choices_to={'finalizado': False}, to='polimento.Jogo_de_Abrasivos')),
            ],
            options={
                'verbose_name': 'Set de Abrasivo',
                'verbose_name_plural': 'Set de Abrasivos',
            },
        ),
        migrations.CreateModel(
            name='Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.PositiveIntegerField(default=1)),
                ('horimetro_inicial', models.FloatField(default=0)),
                ('horimetro_final', models.FloatField(default=0)),
                ('chapas_quebradas', models.PositiveIntegerField(default=0)),
                ('chapas_trincadas', models.PositiveIntegerField(default=0)),
                ('velocidade', models.PositiveIntegerField(default=0)),
                ('frequencia', models.PositiveIntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
                ('operador', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='producao.operador')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polimento.qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='Parada_Politriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polimento_id', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='polimento.polimento')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo_de_Abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('abrasivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.abrasivo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
            options={
                'verbose_name': 'Consumo de Abrasivo',
                'verbose_name_plural': 'Consumo de Abrasivos',
            },
        ),
        migrations.CreateModel(
            name='Chp_Pol_por_Jogo_de_Abr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('cabeca', models.PositiveIntegerField(default=0)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('velocidade', models.PositiveIntegerField(default=0)),
                ('frequencia', models.PositiveIntegerField(default=1)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('jogo_de_abrasivos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.jogo_de_abrasivos')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
                ('tipo_polimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.tipo_polimento')),
            ],
        ),
        migrations.CreateModel(
            name='Chapas_Ini_Fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.PositiveIntegerField(default=0)),
                ('chapa_final', models.PositiveIntegerField(default=0)),
                ('bloco', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('chapa', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='bloco', chained_model_field='bloco', on_delete=django.db.models.deletion.PROTECT, to='chapa.chapa')),
                ('polimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polimento.polimento')),
                ('set_de_abrasivos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.set_de_abrasivos')),
            ],
        ),
    ]
