# Generated by Django 3.2.4 on 2024-12-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troca_de_jogo_de_abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabeca', models.PositiveIntegerField(default=0)),
                ('jogo', models.PositiveBigIntegerField(default=0)),
                ('grao', models.PositiveIntegerField(default=0)),
                ('mudanca_numero', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_de_abrasivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.abrasivo')),
            ],
        ),
    ]
