# Generated by Django 3.2.4 on 2022-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo_de_abrasivos',
            name='pausado',
            field=models.BooleanField(default=False),
        ),
    ]
