# Generated by Django 3.2.4 on 2022-03-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20220112_1005'),
        ('polimento', '0002_jogo_de_abrasivos_pausado'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrasivo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo_de_abrasivos',
            name='valor_abrasivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Chp_Pol_por_Jogo_de_Abr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('velocidade', models.PositiveIntegerField(default=0)),
                ('frequencia', models.PositiveIntegerField(default=1)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('jogo_de_abrasivos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.jogo_de_abrasivos')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polimento.qualidade_polimento')),
                ('tipo_polimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.tipo_polimento')),
            ],
        ),
    ]
