# Generated by Django 3.2.4 on 2024-12-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
        ('polimento', '0002_troca_de_jogo_de_abrasivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca_de_jogo_de_abrasivos',
            name='maquina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.maquina'),
            preserve_default=False,
        ),
    ]
