# Generated by Django 3.2.4 on 2024-12-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0003_troca_de_jogo_de_abrasivos_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca_de_jogo_de_abrasivos',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='troca_de_jogo_de_abrasivos',
            name='mudanca_numero',
            field=models.PositiveIntegerField(default=0, verbose_name='Mudança/Set'),
        ),
    ]
