# Generated by Django 3.2.4 on 2022-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0003_auto_20220301_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo_de_abrasivos',
            old_name='abrasivo_id',
            new_name='abrasivo',
        ),
        migrations.RemoveField(
            model_name='jogo_de_abrasivos',
            name='polimento_id',
        ),
    ]
