# Generated by Django 3.2.4 on 2022-03-01 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0004_auto_20220301_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='chp_pol_por_jogo_de_abr',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
