# Generated by Django 3.2.4 on 2022-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0005_chp_pol_por_jogo_de_abr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chp_pol_por_jogo_de_abr',
            name='cabeca',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
