# Generated by Django 3.2.4 on 2022-03-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0006_chp_pol_por_jogo_de_abr_cabeca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo_de_abrasivos',
            name='cabeca',
        ),
    ]
