# Generated by Django 3.2.4 on 2022-03-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20220112_1005'),
        ('polimento', '0007_remove_jogo_de_abrasivos_cabeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='chp_pol_por_jogo_de_abr',
            name='maquina',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='producao.maquina'),
            preserve_default=False,
        ),
    ]
