# Generated by Django 3.2.4 on 2022-08-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alter_material_material'),
        ('polimento', '0010_jogo_de_abrasivos_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chp_pol_por_jogo_de_abr',
            name='acabamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento'),
        ),
    ]
