# Generated by Django 3.2.4 on 2023-01-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0010_jogo_de_abrasivos_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_polidas',
            name='chapa_final',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chapas_polidas',
            name='chapa_inicial',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chapas_polidas',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapas_polidas',
            name='tipo_polimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.tipo_polimento', verbose_name='Acabamento'),
        ),
    ]
