# Generated by Django 3.2.4 on 2023-01-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0011_auto_20230102_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapas_polidas',
            name='chapa_final',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapas_polidas',
            name='chapa_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
