# Generated by Django 3.2.4 on 2023-01-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0012_auto_20230102_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapas_polidas',
            name='chapa_final',
        ),
        migrations.RemoveField(
            model_name='chapas_polidas',
            name='chapa_inicial',
        ),
        migrations.CreateModel(
            name='Chapas_Ini_Fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.PositiveIntegerField(default=0)),
                ('chapa_final', models.PositiveIntegerField(default=0)),
                ('polimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polimento.polimento')),
            ],
        ),
    ]
