# Generated by Django 3.2.4 on 2023-01-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0013_auto_20230111_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polimento',
            name='Operador',
        ),
    ]
