# Generated by Django 3.2.4 on 2023-01-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('polimento', '0014_remove_polimento_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='polimento',
            name='operador',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='producao.operador'),
        ),
    ]
