# Generated by Django 3.2.4 on 2023-01-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('polimento', '0015_polimento_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('qualidade', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='chp_pol_por_jogo_de_abr',
            name='qualidade',
        ),
        migrations.AddField(
            model_name='polimento',
            name='acabamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento'),
        ),
        migrations.AddField(
            model_name='polimento',
            name='bloco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='producao.bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polimento',
            name='chapas_quebradas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polimento',
            name='chapas_trincadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polimento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polimento',
            name='frequencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='polimento',
            name='velocidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Chapas_Polidas',
        ),
        migrations.DeleteModel(
            name='Qualidade_Polimento',
        ),
    ]
