# Generated by Django 3.2.4 on 2023-02-02 15:50

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0022_alter_resinamento_chapa_bloco'),
        ('chapa', '0011_chapa_pedido'),
        ('polimento', '0020_chapas_ini_fin_chapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_ini_fin',
            name='bloco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='producao.bloco'),
        ),
        migrations.AlterField(
            model_name='chapas_ini_fin',
            name='chapa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='bloco', chained_model_field='bloco', default=319, on_delete=django.db.models.deletion.PROTECT, to='chapa.chapa'),
            preserve_default=False,
        ),
    ]
