# Generated by Django 3.2.4 on 2023-03-15 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0024_auto_20230308_1422'),
        ('polimento', '0021_auto_20230202_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo_de_Abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abrasivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.abrasivo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
            options={
                'verbose_name': 'Abrasivo',
                'verbose_name_plural': 'Abrasivos',
            },
        ),
    ]
