# Generated by Django 3.2.4 on 2023-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0022_consumo_de_abrasivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo_de_abrasivos',
            options={'verbose_name': 'Consumo de Abrasivo', 'verbose_name_plural': 'Consumo de Abrasivos'},
        ),
        migrations.AlterField(
            model_name='consumo_de_abrasivos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
