# Generated by Django 3.2.4 on 2024-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0023_auto_20230328_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_ini_fin',
            name='jogo_abrasivos',
            field=models.ManyToManyField(to='polimento.Jogo_de_Abrasivos'),
        ),
    ]
