# Generated by Django 3.2.4 on 2024-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0024_chapas_ini_fin_jogo_abrasivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapas_ini_fin',
            name='jogo_abrasivos',
            field=models.ManyToManyField(limit_choices_to={'finalizado': False}, to='polimento.Jogo_de_Abrasivos'),
        ),
    ]
