# Generated by Django 3.2.4 on 2024-11-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0025_auto_20241104_1514'),
        ('polimento', '0025_alter_chapas_ini_fin_jogo_abrasivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_de_Abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.maquina')),
                ('set_de_abrasivos', models.ManyToManyField(limit_choices_to={'finalizado': False}, to='polimento.Jogo_de_Abrasivos')),
            ],
        ),
    ]
