# Generated by Django 3.2.4 on 2024-11-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0026_set_de_abrasivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapas_ini_fin',
            name='jogo_abrasivos',
        ),
        migrations.AddField(
            model_name='chapas_ini_fin',
            name='set_de_abrasivos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.set_de_abrasivos'),
        ),
    ]
