# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo_de_Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_de_dentes', models.IntegerField(default=0)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('espessura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField(default=5)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jogo_de_disco_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corte.jogo_de_disco')),
                ('maquina_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Chapas_Cortadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('quantidade_de_ladrilho', models.IntegerField(default=0)),
                ('dimensao_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensao_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('corte_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='corte.corte')),
                ('jogo_de_disco_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corte.jogo_de_disco')),
            ],
        ),
    ]
