# Generated by Django 3.2.4 on 2022-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_cortadas',
            name='dimensao_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapas_cortadas',
            name='dimensao_y',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapas_cortadas',
            name='quantidade_de_ladrilho',
            field=models.IntegerField(default=0),
        ),
    ]
