# Generated by Django 3.2.4 on 2022-08-24 17:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bens', '0004_veiculo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0006_remove_blocoitem_valor'),
        ('estoque', '0005_remove_estoque_qualidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lancamento de Custos',
                'verbose_name_plural': 'Custos',
            },
        ),
        migrations.CreateModel(
            name='Lancamento_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leitura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bens.bem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedreira.lancamento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens do Custo',
            },
        ),
    ]
