# Generated by Django 3.2.4 on 2022-08-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento_item',
            name='leitura',
        ),
    ]
