# Generated by Django 3.2.4 on 2023-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0003_producao_pedreira_m3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao_pedreira_m3',
            options={'verbose_name': 'Lancamento de Produção', 'verbose_name_plural': 'Produção M3'},
        ),
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
