# Generated by Django 3.2.4 on 2023-01-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0004_auto_20230112_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao_pedreira_m3',
            name='m3',
        ),
    ]
