# Generated by Django 3.2.4 on 2023-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0007_alter_producao_pedreira_m3_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento_item',
            name='caixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento_item',
            name='leitura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
