# Generated by Django 3.2.4 on 2023-01-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('pedreira', '0008_auto_20230113_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='material',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='producao.material'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='pedreira',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, to='producao.pedreira'),
        ),
    ]
