# Generated by Django 3.2.4 on 2023-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0009_auto_20230116_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento_item',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
