# Generated by Django 3.2.4 on 2023-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0010_lancamento_item_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='mes',
            field=models.IntegerField(default=2),
        ),
    ]
