# Generated by Django 3.2.4 on 2023-03-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0011_alter_producao_pedreira_m3_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='mes',
            field=models.IntegerField(default=3),
        ),
    ]
