# Generated by Django 3.2.4 on 2023-03-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0012_alter_producao_pedreira_m3_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao_pedreira_m3',
            name='m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='m3',
            field=models.FloatField(default=0),
        ),
    ]
