# Generated by Django 3.2.4 on 2024-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedreira', '0016_alter_producao_pedreira_m3_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='producao_pedreira_m3',
            name='mes',
            field=models.IntegerField(default=11),
        ),
    ]
