# Generated by Django 3.2.4 on 2022-09-13 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0011_auto_20220901_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Envelopamento_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_insumo', models.FloatField(default=0)),
                ('envelopamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envelopamento.envelopamento', verbose_name='Insumo')),
                ('resina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resina')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
    ]
