# Generated by Django 3.2.4 on 2023-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopamento_item',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
