# Generated by Django 3.2.4 on 2023-01-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('envelopamento', '0002_envelopamento_item_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopamento_bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(default=0)),
                ('envelopamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envelopamento.envelopamento')),
                ('resina', models.ForeignKey(default=59, on_delete=django.db.models.deletion.PROTECT, to='producao.resina', verbose_name='Manta')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
    ]
