# Generated by Django 3.2.4 on 2023-01-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polimento', '0013_auto_20230111_1438'),
        ('producao', '0018_delete_chapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_numero', models.IntegerField(default=0)),
                ('comprimento_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comprimento_liquido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_liquida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cavalete', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_list', models.BigIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, max_length=300, null=True)),
                ('exportacao', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('polimento_id', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='polimento.polimento')),
                ('status_chapa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_numero')},
            },
        ),
    ]
