# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento_manual_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField(default=1)),
                ('chapa_final', models.IntegerField(default=1)),
                ('comprimento_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('comprimento_liquido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_liquida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cavalete', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_list', models.BigIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True, max_length=300, null=True)),
                ('exportacao', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('status_chapa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_inicial', 'chapa_final')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento_chapa_quebrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField(default=0)),
                ('chapa_final', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('status_chapa', models.ForeignKey(default='QUEBRADA', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_inicial', 'chapa_final')},
            },
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_numero', models.IntegerField(default=0)),
                ('comprimento_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('comprimento_liquido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura_liquida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cavalete', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_list', models.BigIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True, max_length=300, null=True)),
                ('exportacao', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pedido', models.BigIntegerField(blank=True, null=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('status_chapa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_numero')},
            },
        ),
    ]
