# Generated by Django 3.2.4 on 2023-01-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='polimento_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
