# Generated by Django 3.2.4 on 2023-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0002_alter_chapa_polimento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapa',
            name='polimento_id',
        ),
    ]
