# Generated by Django 3.2.4 on 2023-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0003_remove_chapa_polimento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
