# Generated by Django 3.2.4 on 2023-01-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0005_chapa_serrada_ch_prod_origem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapa',
            name='serrada_ch_prod_origem_id',
        ),
    ]
