# Generated by Django 3.2.4 on 2023-01-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('chapa', '0008_auto_20230120_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento_manual_chapa',
            name='valor_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Lancamento_chapa_quebrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField(default=1)),
                ('chapa_final', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('status_chapa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_inicial', 'chapa_final')},
            },
        ),
    ]
