# Generated by Django 3.2.4 on 2023-03-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('fin_recebimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.adm_empresa'),
        ),
    ]
