# Generated by Django 3.2.4 on 2023-04-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_recebimento', '0002_alter_recebimento_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recebimento',
            options={'verbose_name': 'Contas a Receber', 'verbose_name_plural': 'Recebimentos'},
        ),
        migrations.RenameField(
            model_name='forma_de_pagamento',
            old_name='numero_de_parcelas',
            new_name='numero_da_parcelas',
        ),
        migrations.RemoveField(
            model_name='forma_de_pagamento',
            name='entrada',
        ),
        migrations.AlterField(
            model_name='forma_de_pagamento',
            name='quantidade_de_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forma_de_pagamento',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recebimento_comissao',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recebimento_vencimento',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
