# Generated by Django 3.2.4 on 2023-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0003_auto_20230404_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma_de_pagamento',
            name='percentual_da_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
