# Generated by Django 3.2.4 on 2023-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0005_auto_20230404_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma_de_pagamento',
            name='percentual_da_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recebimento_comissao',
            name='percentual',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
