# Generated by Django 3.2.4 on 2023-04-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0006_auto_20230404_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma_de_pagamento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recebimento_comissao',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recebimento_vencimento',
            name='user',
        ),
    ]
