# Generated by Django 3.2.4 on 2023-04-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_recebimento', '0007_auto_20230404_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento_vencimento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimento_vencimento',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
