# Generated by Django 3.2.4 on 2023-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0008_auto_20230419_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento_comissao',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='recebimento_comissao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
