# Generated by Django 3.2.4 on 2023-04-26 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0009_auto_20230426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento_comissao',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Pagamento_comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('recebimento_comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_recebimento.recebimento')),
            ],
        ),
    ]
