# Generated by Django 3.2.4 on 2023-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_recebimento', '0010_auto_20230426_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='ipi_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pagamento_comissao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
