# Generated by Django 3.2.4 on 2021-11-17 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_de_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField(default=1)),
                ('prazo', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_de_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entrada', models.FloatField(default=100, verbose_name='Entrada %')),
                ('prazo_entrega', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.forma_pagamento')),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.frete')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa', verbose_name='Cliente')),
                ('status_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.status_venda', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status_da_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_da_venda', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_de_venda_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('altura_espessura', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Alt/Esp')),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('percentual_ipi', models.DecimalField(decimal_places=3, default=5, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.grupo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('pedido_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('un', models.ForeignKey(default='M2', on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='OSComercial',
            fields=[
                ('os', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('metragem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_prazo', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(auto_now_add=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADA')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': 'OS',
            },
        ),
        migrations.CreateModel(
            name='OS_Comercial_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('metragem', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.oscomercial')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
