# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0001_initial'),
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_de_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entrada', models.FloatField(default=0, verbose_name='Entrada %')),
                ('prazo_entrega', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.forma_pagamento')),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.frete')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa', verbose_name='Cliente')),
                ('status_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.status_venda', verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status_pv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_da_venda', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda_chapa_mult_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.ManyToManyField(to='chapa.Chapa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('status_chapa', models.ForeignKey(default='RESERVADA', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_de_venda_outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.IntegerField()),
                ('quantidade', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pedido_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_de_venda_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('altura_espessura', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Alt/Esp')),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('metragem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentual_ipi', models.DecimalField(decimal_places=3, default=5, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('outlet', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.grupo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('pedido_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('un', models.ForeignKey(default='M2', on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='OSComercial',
            fields=[
                ('os', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('metragem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_prazo', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(auto_now_add=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADA')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': 'OS',
            },
        ),
        migrations.CreateModel(
            name='OS_Comercial_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('metragem', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.oscomercial')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Forma_de_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.IntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_de_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField(blank=True, max_length=200, null=True)),
                ('pedido_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
            ],
        ),
        migrations.CreateModel(
            name='Venda_chapa_produzida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField(default=0)),
                ('chapa_final', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('chapa', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='bloco', chained_model_field='bloco', on_delete=django.db.models.deletion.PROTECT, to='chapa.chapa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('status_chapa', models.ForeignKey(default='RESERVADA', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_inicial', 'chapa_final')},
            },
        ),
    ]
