# Generated by Django 3.2.4 on 2021-10-26 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSComercial',
            fields=[
                ('os', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_prazo', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(auto_now_add=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADA')], default='P', max_length=1)),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': 'OS',
            },
        ),
        migrations.CreateModel(
            name='OS_Comercial_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.oscomercial')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
