# Generated by Django 3.2.4 on 2021-10-26 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oscomercial',
            old_name='valor',
            new_name='metragem',
        ),
        migrations.AddField(
            model_name='os_comercial_item',
            name='metragem',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='os_comercial_item',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
