# Generated by Django 3.2.4 on 2021-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_de_venda_item',
            name='metragem',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
