# Generated by Django 3.2.4 on 2021-10-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0002_auto_20211026_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os_comercial_item',
            name='user',
        ),
        migrations.AddField(
            model_name='oscomercial',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
