# Generated by Django 3.2.4 on 2021-11-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_pedido_de_venda_item_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_de_venda_item',
            name='user',
        ),
    ]
