# Generated by Django 3.2.4 on 2021-11-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0005_auto_20211110_1116'),
        ('comercial', '0002_status_da_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_de_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField(default=1)),
                ('prazo', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_de_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entrada', models.FloatField(default=100, verbose_name='Entrada %')),
                ('prazo_entrega', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.forma_pagamento')),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.frete')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa', verbose_name='Cliente')),
                ('status_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.status_venda', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
