# Generated by Django 3.2.4 on 2021-11-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0005_auto_20211110_1116'),
        ('comercial', '0003_forma_de_pagamento_pedido_de_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_de_venda_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('altura_espessura', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Alt/Esp')),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('percentual_ipi', models.DecimalField(decimal_places=3, default=5, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento')),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.grupo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
                ('pedido_de_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('un', models.ForeignKey(default='M2', on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
