# Generated by Django 3.2.4 on 2021-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_alter_pedido_de_venda_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_de_venda_item',
            name='metragem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_de_venda_item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
