# Generated by Django 3.2.4 on 2021-11-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_pedido_de_venda_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma_de_pagamento',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='forma_de_pagamento',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forma_de_pagamento',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
