# Generated by Django 3.2.4 on 2021-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_forma_de_pagamento_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma_de_pagamento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
