# Generated by Django 3.2.4 on 2021-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_forma_de_pagamento_valor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status_da_venda',
            new_name='Status_pv',
        ),
        migrations.AlterField(
            model_name='pedido_de_venda',
            name='entrada',
            field=models.FloatField(default=0, verbose_name='Entrada %'),
        ),
    ]
