# Generated by Django 3.2.4 on 2023-01-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('comercial', '0009_auto_20211130_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda_chapa_produzida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField(default=0)),
                ('chapa_final', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('status_chapa', models.ForeignKey(default='RESERVADA', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
            options={
                'unique_together': {('bloco', 'chapa_inicial', 'chapa_final')},
            },
        ),
    ]
