# Generated by Django 3.2.4 on 2023-01-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_venda_chapa_produzida'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda_chapa_produzida',
            name='pedido',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda'),
            preserve_default=False,
        ),
    ]
