# Generated by Django 3.2.4 on 2023-01-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
        ('chapa', '0010_auto_20230124_1212'),
        ('comercial', '0011_venda_chapa_produzida_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda_chapa_mult_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.ManyToManyField(to='chapa.Chapa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pedido_de_venda')),
                ('status_chapa', models.ForeignKey(default='RESERVADA', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa')),
            ],
        ),
    ]
