# Generated by Django 3.2.4 on 2023-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0011_chapa_pedido'),
        ('comercial', '0012_venda_chapa_mult_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda_chapa_produzida',
            name='chapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chapa.chapa'),
        ),
    ]
