# Generated by Django 3.2.4 on 2023-02-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_endereco_de_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco_de_entrega',
            old_name='pedido',
            new_name='pedido_de_venda',
        ),
    ]
