# Generated by Django 3.2.4 on 2023-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('ie', models.CharField(blank=True, max_length=20, null=True)),
                ('im', models.CharField(max_length=20)),
            ],
        ),
    ]
