# Generated by Django 3.2.4 on 2023-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_empresa',
            name='im',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
