# Generated by Django 3.2.4 on 2024-11-22 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0003_userenterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenterprise',
            name='user',
        ),
        migrations.AddField(
            model_name='userenterprise',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
