# Generated by Django 3.2.4 on 2024-11-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20241122_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userenterprise',
            options={'verbose_name': 'Relacionamento Usuário/Empresa'},
        ),
    ]
