# Generated by Django 3.2.4 on 2021-12-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bens', '0003_bem_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0019_req_user'),
        ('producao', '0002_auto_20211122_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('natureza', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAIDA')], default='S', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.empresa')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixa',
            },
        ),
        migrations.CreateModel(
            name='Caixa_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leitura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bens.bem')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.caixa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bens.veiculo')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens do Caixa',
            },
        ),
    ]
