# Generated by Django 3.2.4 on 2021-11-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0003_bem_empresa'),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa_item',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bens.veiculo'),
        ),
    ]
