# Generated by Django 3.2.4 on 2021-11-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_caixa_item_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa_item',
            name='preco',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
