# Generated by Django 3.2.4 on 2021-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='natureza',
            field=models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAIDA')], default='S', max_length=1),
        ),
    ]
