# Generated by Django 3.2.4 on 2021-11-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_alter_caixa_item_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
