# Generated by Django 3.2.4 on 2021-11-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20211122_1334'),
        ('caixa', '0004_alter_caixa_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo'),
        ),
    ]
