# Generated by Django 3.2.4 on 2021-10-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0075_auto_20211019_1610'),
        ('estoque', '0002_classe_do_item_grupo_do_item_item'),
        ('caixa', '0004_caixa_natureza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.caixa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
        ),
    ]
