# Generated by Django 3.2.4 on 2021-10-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_caixa_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='usuario',
        ),
    ]
