# Generated by Django 3.2.4 on 2021-10-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_filial_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='aplicacao',
        ),
        migrations.AddField(
            model_name='caixa_item',
            name='aplicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caixa.aplicacao'),
        ),
    ]
