# Generated by Django 3.2.4 on 2021-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_auto_20211020_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa_item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens do Caixa'},
        ),
        migrations.AddField(
            model_name='caixa_item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
