# Generated by Django 3.2.4 on 2021-10-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0009_auto_20211020_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacao',
            options={'verbose_name': 'Aplicaçao', 'verbose_name_plural': 'Aplicaçao'},
        ),
        migrations.AlterModelOptions(
            name='caixa',
            options={'verbose_name': 'Caixa', 'verbose_name_plural': 'Caixa'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='usuario',
        ),
        migrations.AddField(
            model_name='caixa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caixa_item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
