# Generated by Django 3.2.4 on 2021-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_auto_20211021_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa_item',
            name='leitura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
