# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateField(default=django.utils.timezone.now)),
                ('tema', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ata_item_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.ata')),
            ],
        ),
        migrations.CreateModel(
            name='Ata_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('executado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.ata')),
            ],
        ),
    ]
