# Generated by Django 3.2.4 on 2023-06-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ata',
            old_name='data',
            new_name='data_reuniao',
        ),
    ]
