# Generated by Django 3.2.4 on 2023-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_rename_data_ata_data_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='data_reuniao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
