# Generated by Django 3.2.4 on 2023-06-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0004_alter_ata_data_reuniao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata_item_pessoa',
            name='ata_item',
        ),
        migrations.AddField(
            model_name='ata_item_pessoa',
            name='ata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ata.ata'),
            preserve_default=False,
        ),
    ]
