# Generated by Django 3.2.4 on 2021-06-15 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.utils.tree


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acabamento', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('A', 'PRIMEIRA'), ('B', 'SEGUNDA LINHA')], default='A', max_length=1)),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centro_de_Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_custo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.aplicacao')),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.centro_de_custo')),
            ],
        ),
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(default='60000', max_length=6)),
                ('endereco', models.CharField(max_length=200)),
                ('uf', models.CharField(default='CE', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espessura',
            fields=[
                ('espessura', models.DecimalField(decimal_places=3, default=0.02, max_digits=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fio_diamantado',
            fields=[
                ('jogo_fio', models.IntegerField(primary_key=True, serialize=False)),
                ('espessura_fio', models.DecimalField(decimal_places=3, max_digits=6)),
                ('referencia', models.CharField(max_length=50)),
                ('nota_fiscal', models.IntegerField()),
                ('status_fio', models.CharField(choices=[('A', 'ATIVO'), ('F', 'FINALIZADO')], default='A', max_length=1)),
                ('valor_metro_fio', models.FloatField()),
                ('quantidade_fio', models.IntegerField(default=0)),
                ('comprimento_fio', models.FloatField(default=0)),
                ('garantia', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField(default=1)),
                ('intervalo', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Linha_Resinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=100)),
                ('lacada', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('dureza', models.IntegerField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('mes', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observacao_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao_chapa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrada', models.FloatField(default=100, verbose_name='Entrada %')),
                ('prazo_entrega', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.forma_pagamento')),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.frete')),
            ],
        ),
        migrations.CreateModel(
            name='Pedreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedreira', models.CharField(max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpjcpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status_bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status_chapa',
            fields=[
                ('status', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_venda', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=20)),
                ('fator', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('descricao_unidade', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serrada', models.IntegerField()),
                ('comprimento', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('horimetro_inicial', models.IntegerField()),
                ('horimetro_final', models.IntegerField()),
                ('amperagem_max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('espessura_fio_inicial', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('espessura_fio_final', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('qtde_fios', models.IntegerField()),
                ('observacoes', models.TextField()),
                ('periferica', models.DecimalField(decimal_places=3, max_digits=5)),
                ('cala', models.IntegerField(default=10)),
                ('velocidade', models.FloatField(default=0)),
                ('consumo_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('centro_de_custo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producao.centro_de_custo')),
                ('jogo_fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.fio_diamantado')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Resinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.linha_resinamento')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.mes')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.classe')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.grupo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_venda_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('altura_espessura', models.FloatField(verbose_name='Alt/Esp')),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('identificacao', models.CharField(max_length=20)),
                ('percentual_ipi', models.FloatField(default=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.grupo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.material')),
                ('pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pedido_venda')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='pedido_venda',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pessoa', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido_venda',
            name='status_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.status_venda', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.serrada')),
            ],
        ),
        migrations.AddField(
            model_name='operador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.setor'),
        ),
        migrations.CreateModel(
            name='Folha_de_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2021)),
                ('qtde_funcionarios', models.IntegerField()),
                ('folha', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('centro_de_custo', models.ForeignKey(default=1, on_delete=django.utils.tree.Node, to='producao.centro_de_custo')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.mes')),
            ],
        ),
        migrations.CreateModel(
            name='FioFatorConversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureza', models.IntegerField()),
                ('fator', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pessoa')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
            ],
        ),
        migrations.AddField(
            model_name='fio_diamantado',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.liga'),
        ),
        migrations.AddField(
            model_name='fio_diamantado',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina'),
        ),
        migrations.AddField(
            model_name='fio_diamantado',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pessoa'),
        ),
        migrations.CreateModel(
            name='Estoque_ladrilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.detalhe')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.material')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.detalhe')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_ladrilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.detalhe')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.material')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('comprimento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('espessura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.detalhe')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='DespesaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('preco', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.despesa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='pedreira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.pedreira'),
        ),
        migrations.CreateModel(
            name='Chapas_produzidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('espessura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.espessura')),
                ('serrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.serrada')),
            ],
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.acabamento')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('espessura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.espessura')),
                ('observacao_chapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.observacao_chapa')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='bloco',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.material'),
        ),
        migrations.AddField(
            model_name='bloco',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.status_bloco'),
        ),
    ]
