# Generated by Django 3.2.4 on 2022-01-12 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='custos_pedreira',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='folha_de_pagamento',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
    ]
