# Generated by Django 3.2.4 on 2021-11-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resina_valor',
            name='ipi',
        ),
    ]
