# Generated by Django 3.2.4 on 2021-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_remove_resina_valor_ipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resina_valor',
            name='ipi',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=6),
        ),
    ]
