# Generated by Django 3.2.4 on 2022-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20220112_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
