# Generated by Django 3.2.4 on 2021-06-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_auto_20210618_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_produzidas',
            name='bloco',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='producao.bloco'),
        ),
    ]
