# Generated by Django 3.2.4 on 2021-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_resina_valor_ipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resina_valor',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
