# Generated by Django 3.2.4 on 2021-11-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0004_resina_valor_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resina_valor',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens de Resinamento'},
        ),
        migrations.AddField(
            model_name='pedido_venda_item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resina_valor',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
