# Generated by Django 3.2.4 on 2022-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_resinamento_acabamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
