# Generated by Django 3.2.4 on 2021-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_chapas_produzidas_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serrada',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='serrada',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='serrada',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='serrada',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='serrada',
            name='velocidade',
        ),
        migrations.AlterField(
            model_name='fio_diamantado',
            name='referencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
