# Generated by Django 3.2.4 on 2021-06-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_auto_20210618_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.status_bloco'),
        ),
        migrations.AlterField(
            model_name='blocoserrada',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
        migrations.AlterField(
            model_name='blocoserrada',
            name='serrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.serrada'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='espessura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.espessura'),
        ),
        migrations.AlterField(
            model_name='chapa',
            name='observacao_chapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.observacao_chapa'),
        ),
        migrations.AlterField(
            model_name='chapas_produzidas',
            name='bloco',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
        migrations.AlterField(
            model_name='chapas_produzidas',
            name='espessura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.espessura'),
        ),
        migrations.AlterField(
            model_name='chapas_produzidas',
            name='serrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.serrada'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.aplicacao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='centro_de_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='pedreira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pedreira'),
        ),
        migrations.AlterField(
            model_name='despesaitem',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.despesa'),
        ),
        migrations.AlterField(
            model_name='despesaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.produto'),
        ),
        migrations.AlterField(
            model_name='despesaitem',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade'),
        ),
        migrations.AlterField(
            model_name='estoque_ladrilho',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acabamento'),
        ),
        migrations.AlterField(
            model_name='estoque_ladrilho',
            name='detalhe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.detalhe'),
        ),
        migrations.AlterField(
            model_name='estoque_ladrilho',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material'),
        ),
        migrations.AlterField(
            model_name='estoque_ladrilho',
            name='qualidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.qualidade'),
        ),
        migrations.AlterField(
            model_name='fio_diamantado',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.liga'),
        ),
        migrations.AlterField(
            model_name='fio_diamantado',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.maquina'),
        ),
        migrations.AlterField(
            model_name='fio_diamantado',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.classe'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.grupo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.unidade'),
        ),
        migrations.AlterField(
            model_name='serrada',
            name='centro_de_custo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo'),
        ),
        migrations.AlterField(
            model_name='serrada',
            name='jogo_fio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.fio_diamantado'),
        ),
        migrations.AlterField(
            model_name='serrada',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.maquina'),
        ),
    ]
