# Generated by Django 3.2.4 on 2022-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocoitem',
            name='valor',
        ),
    ]
