# Generated by Django 3.2.4 on 2022-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_remove_blocoitem_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_chapa',
            name='comprimento_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='entrada_chapa',
            name='espessura_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='entrada_chapa',
            name='largura_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
