# Generated by Django 3.2.4 on 2022-08-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_auto_20220824_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada_chapa',
            name='comprimento_bruto',
        ),
        migrations.RemoveField(
            model_name='entrada_chapa',
            name='espessura_bruto',
        ),
        migrations.RemoveField(
            model_name='entrada_chapa',
            name='largura_bruto',
        ),
    ]
