# Generated by Django 3.2.4 on 2021-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_auto_20210706_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view_serrada',
            name='id',
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='altura',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='amperagem_max',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='bloco',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='comprimento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='custo_bloco',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='custo_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='largura',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='m2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='m3_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='m3_liquido',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='m3_perda',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='qtde_chapas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='view_serrada',
            name='jogo_fio_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='view_serrada',
            name='maquina',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='view_serrada',
            name='serrada',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='view_serrada',
            table='view_serrada',
        ),
    ]
