# Generated by Django 3.2.4 on 2021-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_auto_20210707_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_serrada',
            name='material',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='view_serrada',
            name='prd_fio_m2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
