# Generated by Django 3.2.4 on 2022-09-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_auto_20220824_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resinamento_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_numero', models.IntegerField()),
                ('resinamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resinamento', verbose_name='Chapa número')),
            ],
        ),
    ]
