# Generated by Django 3.2.4 on 2022-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_resinamento_chapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resinamento_chapa',
            name='chapa_numero',
        ),
        migrations.AddField(
            model_name='resinamento_chapa',
            name='chapa_final',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resinamento_chapa',
            name='chapa_inicial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
