# Generated by Django 3.2.4 on 2022-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_auto_20220901_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='tipo',
            field=models.CharField(choices=[('A', 'PRIMEIRA'), ('B', 'SEGUNDA LINHA'), ('C', 'TERCEIRA LINHA')], default='A', max_length=1),
        ),
    ]
