# Generated by Django 3.2.4 on 2021-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_alter_view_serrada_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serrada',
            name='qtde_fios',
        ),
        migrations.AddField(
            model_name='chapas_produzidas',
            name='qtde_fios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='mercado',
            field=models.CharField(choices=[('I', 'INTERNO'), ('E', 'EXTERNO'), ('G', 'GERAL')], default='I', max_length=1),
        ),
    ]
