# Generated by Django 3.2.4 on 2022-12-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_alter_bloco_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Cavalete',
            fields=[
                ('status_cavalete', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cavalete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavalete', models.CharField(max_length=50)),
                ('status_cavalete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.status_cavalete')),
            ],
        ),
        migrations.AddField(
            model_name='chapa',
            name='cavalete',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='producao.cavalete'),
            preserve_default=False,
        ),
    ]
