# Generated by Django 3.2.4 on 2021-07-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_auto_20210708_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view_serrada',
            options={'managed': False},
        ),
    ]
