# Generated by Django 3.2.4 on 2021-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_alter_view_serrada_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_producao_fio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m3_bruto', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('m3_liquido', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('m2', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('jogo_fio_id', models.IntegerField()),
                ('qtde_fios', models.IntegerField()),
                ('maquina', models.CharField(max_length=100)),
                ('espessura_fio_inicial', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('espessura_fio_final', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('prd_fio_m2', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('custo_m2', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'view_producao_fio',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='faturamento',
            name='valor_externo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='valor_interno',
            field=models.FloatField(default=0),
        ),
    ]
