# Generated by Django 3.2.4 on 2023-01-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_auto_20221227_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='status_chapa',
            field=models.ForeignKey(default='DISPONIVEL', on_delete=django.db.models.deletion.PROTECT, to='producao.status_chapa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapa',
            name='cavalete',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='producao.cavalete'),
        ),
        migrations.AlterField(
            model_name='custos_pedreira',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='folha_de_pagamento',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
    ]
