# Generated by Django 3.2.4 on 2021-07-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_auto_20210709_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamento',
            name='mercado',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='valor',
        ),
    ]
