# Generated by Django 3.2.4 on 2023-01-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_auto_20230102_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapa',
            unique_together={('bloco', 'chapa')},
        ),
    ]
