# Generated by Django 3.2.4 on 2021-07-12 17:19

from django.db import migrations, models
import django.db.models.deletion
import producao.models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_auto_20210709_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha_de_pagamento',
            name='mes',
            field=models.IntegerField(choices=[('1', 'JANEIRO'), ('2', 'FEVEREIRO'), ('3', 'MARÇO'), ('4', 'ABRIL'), ('5', 'MAIO'), ('6', 'JUNHO'), ('7', 'JULHO'), ('8', 'AGOSTO'), ('9', 'SETEMBRO'), ('10', 'OUTUBRO'), ('11', 'NOVEMBRO'), ('12', 'DEZEMBRO')]),
        ),
        migrations.CreateModel(
            name='Custos_Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2021)),
                ('mes', models.IntegerField(choices=[('1', 'JANEIRO'), ('2', 'FEVEREIRO'), ('3', 'MARÇO'), ('4', 'ABRIL'), ('5', 'MAIO'), ('6', 'JUNHO'), ('7', 'JULHO'), ('8', 'AGOSTO'), ('9', 'SETEMBRO'), ('10', 'OUTUBRO'), ('11', 'NOVEMBRO'), ('12', 'DEZEMBRO')])),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pedreira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pedreira')),
            ],
        ),
    ]
