# Generated by Django 3.2.4 on 2023-01-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_alter_chapa_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tela_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField()),
                ('chapa_final', models.IntegerField()),
                ('quantidade_insumo', models.FloatField(default=0)),
                ('resina', models.ForeignKey(default=59, on_delete=django.db.models.deletion.PROTECT, to='producao.resina', verbose_name='Tela')),
                ('resinamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resinamento', verbose_name='Chapa número')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
    ]
