# Generated by Django 3.2.4 on 2023-01-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_tela_chapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela_chapa',
            name='resina',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='producao.resina', verbose_name='Tela'),
        ),
        migrations.AlterField(
            model_name='tela_chapa',
            name='unidade',
            field=models.ForeignKey(default='M', on_delete=django.db.models.deletion.PROTECT, to='producao.unidade'),
        ),
        migrations.AlterField(
            model_name='un',
            name='unidade',
            field=models.CharField(default='M', max_length=20, primary_key=True, serialize=False),
        ),
    ]
