# Generated by Django 3.2.4 on 2021-07-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_auto_20210712_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folha_de_pagamento',
            name='mes',
        ),
    ]
