# Generated by Django 3.2.4 on 2021-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_remove_folha_de_pagamento_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_producao',
            name='mes',
            field=models.IntegerField(choices=[(1, 'JANEIRO'), (2, 'FEVEREIRO'), (3, 'MARÇO'), (4, 'ABRIL'), (5, 'MAIO'), (6, 'JUNHO'), (7, 'JULHO'), (8, 'AGOSTO'), (9, 'SETEMBRO'), (10, 'OUTUBRO'), (11, 'NOVEMBRO'), (12, 'DEZEMBRO')]),
        ),
    ]
