# Generated by Django 3.2.4 on 2023-01-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_auto_20230111_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapa',
        ),
    ]
