# Generated by Django 3.2.4 on 2023-01-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0018_delete_chapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento_item',
            name='preco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.resina_valor'),
        ),
    ]
