# Generated by Django 3.2.4 on 2023-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0019_resinamento_item_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento_item',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
