# Generated by Django 3.2.4 on 2023-02-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_alter_resinamento_item_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento_chapa',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
    ]
