# Generated by Django 3.2.4 on 2023-02-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0021_resinamento_chapa_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento_chapa',
            name='bloco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
    ]
