# Generated by Django 3.2.4 on 2021-07-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0021_auto_20210712_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedreira',
            name='centro_de_custo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.centro_de_custo'),
        ),
    ]
