# Generated by Django 3.2.4 on 2023-03-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_remove_resinamento_chapa_bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao_pedreira',
            name='m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producao_pedreira',
            name='m3',
            field=models.FloatField(default=0),
        ),
    ]
