# Generated by Django 3.2.4 on 2021-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_auto_20210715_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producao_pedreira',
            old_name='custos_producao_pedreira_id',
            new_name='custos_pedreira',
        ),
    ]
