# Generated by Django 3.2.4 on 2021-07-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0024_rename_custos_producao_pedreira_id_producao_pedreira_custos_pedreira'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pedreira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.pedreira'),
        ),
    ]
