# Generated by Django 3.2.4 on 2021-07-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0026_resinamento_item_quantidade_insumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resinamento_item',
            old_name='quantidade',
            new_name='quantidade_de_chapas',
        ),
    ]
