# Generated by Django 3.2.4 on 2021-07-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0027_rename_quantidade_resinamento_item_quantidade_de_chapas'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_producao_fio_resumo',
            fields=[
                ('maquina', models.CharField(max_length=100)),
                ('jogo_fio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('liga', models.CharField(max_length=25)),
                ('valor_metro_fio', models.FloatField(default=0)),
                ('m3_bruto', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('m3_liquido', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('m2', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('garantia_do_fio', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('espessura_fio', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('prd_fio_m2', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('prd_fio_m2_dureza', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('dureza', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'view_producao_fio_resumo',
                'managed': False,
            },
        ),
    ]
