# Generated by Django 3.2.4 on 2021-08-16 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0028_view_producao_fio_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resinamento',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='resinamento',
            name='mes',
        ),
        migrations.AddField(
            model_name='resinamento',
            name='data',
            field=models.IntegerField(default=datetime.datetime(2021, 8, 16, 12, 32, 34, 414002, tzinfo=utc)),
        ),
    ]
