# Generated by Django 3.2.4 on 2021-08-16 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0029_auto_20210816_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 12, 33, 45, 88055, tzinfo=utc)),
        ),
    ]
