# Generated by Django 3.2.4 on 2021-08-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0030_alter_resinamento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resinamento',
            name='data',
        ),
    ]
