# Generated by Django 3.2.4 on 2021-08-16 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0031_remove_resinamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 12, 43, 31, 216418, tzinfo=utc)),
        ),
    ]
