# Generated by Django 3.2.4 on 2021-08-16 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0032_resinamento_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serrada',
            old_name='consumo_kwh',
            new_name='consumo_kwh_fp',
        ),
        migrations.AddField(
            model_name='serrada',
            name='consumo_kwh_p',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 13, 0, 14, 52866, tzinfo=utc)),
        ),
    ]
