# Generated by Django 3.2.4 on 2021-08-16 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0033_auto_20210816_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento',
            name='frequencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 13, 6, 41, 882482, tzinfo=utc)),
        ),
    ]
