# Generated by Django 3.2.4 on 2021-08-16 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0034_auto_20210816_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resinamento',
            name='frequencia',
        ),
        migrations.AddField(
            model_name='resinamento_item',
            name='frequencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 13, 10, 22, 371727, tzinfo=utc)),
        ),
    ]
