# Generated by Django 3.2.4 on 2021-08-16 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0035_auto_20210816_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 13, 10, 34, 290923, tzinfo=utc)),
        ),
    ]
