# Generated by Django 3.2.4 on 2021-08-16 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0036_alter_resinamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 13, 18, 54, 578537, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Parada_Resinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resinamento_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resinamento')),
            ],
        ),
    ]
