# Generated by Django 3.2.4 on 2021-10-18 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0063_auto_20211015_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resina_valor',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 18, 39, 59, 796617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 18, 39, 59, 796617, tzinfo=utc)),
        ),
    ]
