# Generated by Django 3.2.4 on 2021-10-19 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0067_auto_20211018_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resina_valor',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 18, 47, 20, 977957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 18, 47, 20, 977957, tzinfo=utc)),
        ),
    ]
