# Generated by Django 3.2.4 on 2021-10-19 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0068_auto_20211019_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resina_valor',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 18, 56, 31, 364066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 19, 18, 56, 31, 365064, tzinfo=utc)),
        ),
    ]
