# Generated by Django 3.2.4 on 2021-10-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_caixa_item_leitura'),
        ('bens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='Filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.filial'),
        ),
    ]
