# Generated by Django 3.2.4 on 2021-11-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='empresa',
        ),
    ]
