# Generated by Django 3.2.4 on 2021-10-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0002_bem_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='localizacao',
        ),
    ]
