# Generated by Django 3.2.4 on 2021-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0003_bem_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
