# Generated by Django 3.2.4 on 2023-01-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0005_auto_20230130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bens.veiculo'),
        ),
    ]
