# Generated by Django 3.2.4 on 2023-01-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0006_bem_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='modelo',
        ),
    ]
