# Generated by Django 3.2.4 on 2024-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade_de_chapas', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.linha_resinamento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Telamento_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_insumo', models.FloatField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('resina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resina')),
                ('telamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telamento.telamento', verbose_name='Insumo')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Telamento_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField()),
                ('chapa_final', models.IntegerField()),
                ('quantidade_insumo', models.FloatField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('resina', models.ForeignKey(default=59, on_delete=django.db.models.deletion.PROTECT, to='producao.resina', verbose_name='Tela')),
                ('telamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telamento.telamento', verbose_name='Chapa número')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
    ]
