# Generated by Django 3.2.4 on 2022-09-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telamento_chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_inicial', models.IntegerField()),
                ('chapa_final', models.IntegerField()),
                ('telamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telamento.telamento', verbose_name='Chapa número')),
            ],
        ),
    ]
