# Generated by Django 3.2.4 on 2023-01-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telamento', '0003_auto_20230105_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='telamento_chapa',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='telamento_item',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
