# Generated by Django 3.2.4 on 2021-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='hora_chegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
