# Generated by Django 3.2.4 on 2021-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(default='.', max_length=50),
        ),
    ]
