# Generated by Django 3.2.4 on 2021-10-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_veiculo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='filial',
        ),
    ]
