# Generated by Django 3.2.4 on 2021-10-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bens', '0004_veiculo'),
        ('controle', '0003_remove_veiculo_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bens.veiculo'),
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
