# Generated by Django 3.2.4 on 2021-10-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor_pessoal', '0006_auto_20210929_1442'),
        ('controle', '0003_remove_veiculo_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('os', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_prazo', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(auto_now_add=True, null=True)),
                ('descricao', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADA')], default='P', max_length=1)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor_pessoal.cadastro_funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle.veiculo')),
            ],
        ),
    ]
