# Generated by Django 3.2.4 on 2021-10-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OS',
        ),
    ]
