# Generated by Django 3.2.4 on 2024-12-09 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sesmt.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor_pessoal', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/', validators=[sesmt.validator.validate_pdf], verbose_name='Arquivo PDF')),
                ('emissao_documento', models.DateField(default=datetime.datetime.now, help_text='Data de emissão do documento que se refere ao mês e ano do documento.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(help_text='Somente arquivo PDF é aceito!', on_delete=django.db.models.deletion.CASCADE, to='cadastro.adm_empresa', verbose_name='Empresa')),
                ('title', models.ForeignKey(help_text='Selecione o tipo de documento', on_delete=django.db.models.deletion.CASCADE, to='sesmt.title', verbose_name='Título')),
                ('worker', models.ForeignKey(help_text='Selecione o funcionário relacionado ao PDF.', on_delete=django.db.models.deletion.CASCADE, to='setor_pessoal.cadastro_funcionario', verbose_name='Funcionário')),
            ],
        ),
    ]
