# Generated by Django 3.2.4 on 2024-11-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titulo',
            new_name='Title',
        ),
    ]
