# Generated by Django 3.2.4 on 2024-11-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0003_alter_pdfdocument_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='title',
        ),
    ]
