# Generated by Django 3.2.4 on 2024-11-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0004_remove_pdfdocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sesmt.title', verbose_name='Título'),
            preserve_default=False,
        ),
    ]
