# Generated by Django 3.2.4 on 2024-11-21 12:37

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_adm_empresa_im'),
        ('setor_pessoal', '__first__'),
        ('sesmt', '0005_pdfdocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='emissao_documento',
            field=models.DateField(auto_now_add=True, default=now, help_text='Data de emissão do documento que se refere ao mês e ano do documento.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='enterprise',
            field=models.ForeignKey(help_text='Somente arquivo PDF é aceito!', on_delete=django.db.models.deletion.CASCADE, to='cadastro.adm_empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='title',
            field=models.ForeignKey(help_text='Selecione o tipo de documento', on_delete=django.db.models.deletion.CASCADE, to='sesmt.title', verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='worker',
            field=models.ForeignKey(help_text='Selecione o funcionário relacionado ao PDF.', on_delete=django.db.models.deletion.CASCADE, to='setor_pessoal.cadastro_funcionario', verbose_name='Funcionário'),
        ),
    ]
