# Generated by Django 3.2.4 on 2024-11-21 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0006_auto_20241121_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime.now, help_text='Data de referência do documento.'),
        ),
    ]
